version: '2'
services:

  # We will use latest tag of currently deployed docker image
  base_uwsgi:
    image: kartoza/hydro_django:latest

  uwsgi:
    build:
      context: docker
      dockerfile: Dockerfile-dev
    image: hydro_dev_uwsgi
